name       : python-cryptography-vectors
version    : 3.4.8
release    : 3
source     :
    - https://pypi.io/packages/source/c/cryptography-vectors/cryptography_vectors-3.4.8.tar.gz : 4c84410257993d3de058b44b777a49e1da2ae35ebea2970a360c7e3aa0f580f2
homepage   : https://github.com/pyca/cryptography
license    : Apache-2.0
component  : programming.python
summary    : Test vectors for the cryptography package
description: |
    Test vectors for the cryptography package
builddeps  :
    - pkgconfig(python3)
install    : |
    %python3_install
