name       : python-cryptography-vectors
version    : 3.4.7
release    : 1
source     :
    - https://pypi.io/packages/source/c/cryptography-vectors/cryptography_vectors-3.4.7.tar.gz : a7ac3aaa57514687696ad65f833e5e39b6fa3c5d41de2b8c938346ee119204c2
homepage   : https://github.com/pyca/cryptography
license    : Apache-2.0
component  : programming.python
summary    : Test vectors for the cryptography package
description: |
    Test vectors for the cryptography package
builddeps  :
    - pkgconfig(python3)
install    : |
    %python3_install
