name       : python-cryptography-vectors
version    : 41.0.3
release    : 4
source     :
    - https://pypi.io/packages/source/c/cryptography-vectors/cryptography_vectors-41.0.3.tar.gz : 80de0452c4b34f56f5518e81ebd75b6b905f5728aaed521d42e41f4ebc8a43fb
homepage   : https://github.com/pyca/cryptography
license    : Apache-2.0
component  : programming.python
summary    : Test vectors for the cryptography package
description: |
    Test vectors for the cryptography package
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build    : |
    %python3_setup
install    : |
    %python3_install
